### ISSUE TITLE
Implement changes to accomodate new CircleCI UI

### ISSUE THREAD

**Issue by joeltimothyoh** [startersclan/docker-sourceservers#13]
A number of changes will have to be performed to accommodate CircleCI's move to its new UI:

1. Update CircleCI build badge links 
1. Utilize [Slack orb](https://circleci.com/orbs/registry/orb/circleci/slack) for Slack notifications if necessary

See: https://discuss.circleci.com/t/access-to-the-old-ui-will-be-shut-down-on-august-14th/36673

**Comment by joeltimothyoh** [comment]
Slack notifications for workflows still appear to be functioning despite the removal of the old slack integration options under project settings. Seems like they're pushing users to utilizing the Slack orb instead. I wouldn't say this is too urgent, since email notifications for workflows are still coming in as well.

See: https://support.circleci.com/hc/en-us/articles/360047082992-Send-slack-notification-at-end-of-workflow

@leojonathanoh

**Comment by leojonathanoh** [comment]
yep, wait for the orbs stuff to mature first @joeltimothyoh

**Comment by joeltimothyoh** [comment]
> yep, wait for the orbs stuff to mature first @joeltimothyoh

I think it already is pretty mature,. Based on the first link it's able to send a post notification for a workflow. it's just if the job fails the notification fails to send which makes less reliable than the old slack integration or email. An addition as elaborate as this shouldn't be a step backward for something basic offered by most alternative CI providers.

**Comment by joeltimothyoh** [comment]
The [Circle CI app](https://github.com/marketplace/circleci) has been installed for the organization. Adding an orb may no longer be necessary for job notifications from CircleCI.

Now awaiting for the next game update to ascertain notifications from CircleCI checks work correctly.

**Comment by leojonathanoh** [comment]
@joeltimothyoh seems to be working. Only issue is the URLs on the notification has google analytics.

**Comment by joeltimothyoh** [comment]
> @joeltimothyoh seems to be working. Only issue is the URLs on the notification has google analytics. 

I don't see any notification. Link? @leojonathanoh

**Comment by leojonathanoh** [comment]
https://discord.com/channels/678934485512880128/682041430021242980/874794884576444426

**Comment by joeltimothyoh** [comment]
Ok. No notification on teams though. @leojonathanoh

**Comment by joeltimothyoh** [comment]
I tried enabling the project setting 'GitHub Status Updates' for the `build` job which completed much later after the `update` job:

![image](https://user-images.githubusercontent.com/24771499/128950702-abf608cb-f6a8-4eb3-a066-c82808c3c1f2.png)

However, according to https://circleci.com/docs/2.0/enable-checks/#to-disable-github-checks-for-a-project, enabling the setting disables checks. Yet, we received two notifications for the `update` job (https://discord.com/channels/678934485512880128/682041430021242980/874794884207374346, https://discord.com/channels/678934485512880128/682041430021242980/874794884576444426) but only 1 for the `build` job (https://discord.com/channels/678934485512880128/682041430021242980/874805522367397928). The `build` job's only notification however pertains to the workflow and so contradicts what's documented in https://circleci.com/docs/2.0/enable-checks/#to-disable-github-checks-for-a-project:

> * GitHub Checks are administered from the GitHub UI, and are reported in the GitHub UI per workflow.
> * GitHub status updates are the default way status updates from your builds are reported in the GitHub UI, and they are reported per job.

Either way, I've re-disabled the setting. Travis CI appears to send both notifications. The defaults are safe.

Since we're using discord for the community, with the CircleCI job notifications now appearing in the channel, this issue can be closed.

**Comment by joeltimothyoh** [comment]
Ok, perhaps the documentation is right in saying enabling the option in https://github.com/startersclan/docker-sourceservers/issues/13#issuecomment-896401592 disables GitHub Checks for CircleCI since the equivalent of the 'CircleCI Checks checks on master` notification was missing for the `update` job. Yet, with the setting disabled (which is the default setting), both notifications come in. It's as though this setting but overrides to *only* enable GitHub status updates API calls for the project.

Keeping it simple.

Closing.

**Comment by leojonathanoh** [comment]
@joeltimothyoh all of these interactive configuration is why i dont like these externals CIs - you get a disintegrated ci experience and then have to manually configure so many things by hand. It's much easier to express a pipeline in a yaml.
