### ISSUE TITLE
Clients cannot connect to server

### ISSUE THREAD

**Issue by ggMartinez** [startersclan/docker-sourceservers#27]
Hello, I'm trying to run a Half Life 2 Deathmatch Server, in a Centos 7 box.

The image works well, and the server start successfully, but when trying to connect from the game, there's no response, and the server's console don't show any player trying to connect.

This is how I'm trying to run it: 
`docker run -it  --rm  -p 27015:27015/udp  --name "HL2" sourceservers/hl2mp 'srcds_run -game hl2mp -port 27015'`

Don't know if there is something missing. 

Thank you for any help.

**Comment by leojonathanoh** [comment]
@ggMartinez perhaps you can try adding a starting map using `+map` cvar. 

```
srcds_run -console -usercon -secure -game hl2mp -port 27015 +map dm_lockdown -maxplayers 16 +sv_lan 0
```
and enter `status` command in the server console. Ensure those cvars match the server `status`.

**Comment by ggMartinez** [comment]
That worked, thank you!

**Comment by leojonathanoh** [comment]
glad it worked for you. You can also try the preliminary `docker-compose.yml` example in #26
